### ISSUE TITLE
Map areas are adding spaces below the imagemap

### ISSUE THREAD

**Issue by dhinostroza** [denshade/redcap_customimagemap#5] opened 2024-06-04 19:00 UTC
Hi,
Testing the Choir male body, a line is added below the image for each area within the map. You can see in the screenshot below that there is a lot of space underneath the image, even though only the areas for the frontal body have been mapped!
If I manually remove the "empty" space using the rich text editor, I delete the area mappings. Is there a way of forcing the field to display a truncated height?
![Screenshot 2024-06-04 at 1 49 39 PM](https://github.com/redcapuzgent/redcap_customimagemap/assets/18691188/7b27c6de-00ff-43be-8d6f-38fd6563dc82)

**Comment by steentje34** [comment] 2024-06-05 05:59
Hi @dhinostroza, thanks for reaching out! This is a known issue, caused by the fact that REDCap replaces newlines in the code by BR elements. It can be resolved by removing newlines from the HTML code, as mentioned on the module's how to page:
> Remove newlines from the HTML code. They are replaced by BR elements and ruin your syntax.

If you have any other questions or remarks, please do not hesitate to contact me.

**Closed as completed by steentje34** 2024-06-05 05:59 UTC
Labels: question

**Comment by dhinostroza** [comment] 2024-06-05 14:18
Thank you, Simon,
Yes, that worked!
For future readers, my mistake was that I was removing the newlines from the designer end-layout, and not from the field where the code was placed. Thus, the code in the imagemap field should be in a single line, like this:
![Screenshot 2024-06-05 at 9 18 55 AM](https://github.com/redcapuzgent/redcap_customimagemap/assets/18691188/f02135d2-d2dc-4f53-8a59-c3d4318f949b)
